name: drug_pipeline
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - pytorch
  - cpuonly  
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - numpy
  - pip