name: drug_pipeline
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - rdkit
  - scikit-learn
  - matplotlib
  - pandas
  - numpy
  - pytorch
  - torchvision
  - torchaudio
